### ISSUE TITLE
Sample data not available

### ISSUE THREAD

**Issue by josecared** [davebryantlab/Traject3d#1]
Hello. The link to the sample data doesnt wok anymore...

**Comment by efreckmann** [comment]
Apologies Jose, we migrated the sample data and neglected to update the link - thank you for bringing this to our attention! I have now updated it so you should be able to access the data. If you could confirm that this is working for you that would be a great help.

Kind regards, 
Eva

**Comment by josecared** [comment]
Hello again! I have access to the data now. Thank you!

**Comment by efreckmann** [comment]
Great, thank you for confirming!
